scorecard:
  # Setting a global scorecard option
  output: json
  plugins:
    # `basic` tests configured to test 2 CRs
    - basic:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_cataloguis_crd.yaml"
    # `olm` tests configured to test 2 CRs
    - olm:
        cr-manifest:
          - "deploy/crds/operator.ibm.com_cataloguis_crd.yaml"
        csv-path: "deploy/olm-catalog/ibm-catalog-operator/0.0.1/ibm-catalog-operator.v0.0.1.clusterserviceversion.yaml"
