apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: icpcatalogcharts.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: IcpCatalogChart
    listKind: IcpCatalogChartList
    plural: icpcatalogcharts
    singular: icpcatalogchart
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      type: object
      x-kubernetes-preserve-unknown-fields: true  
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
