apiVersion: operator.ibm.com/v1alpha1
kind: CatalogUI
metadata:
  name: catalog-ui
  annotations:
    helm.operator-sdk/upgrade-force: "True"
  labels:
    app.kubernetes.io/instance: catalog-ui
    app.kubernetes.io/managed-by: cataloguis.operator.ibm.com
    app.kubernetes.io/name: catalog-ui
spec:
  catalogui:
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi
  replicaCount: 1