kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ibm-catalog-ui-operator
subjects:
- kind: ServiceAccount
  name: ibm-catalog-ui-operator
  namespace: ibm-common-services
roleRef:
    kind: ClusterRole
    name: ibm-catalog-ui-operator
    apiGroup: rbac.authorization.k8s.io