catalogui:
  commonname: catalog-ui
  env:
    catalogApiRouteUrl: https://icp-management-ingress:443/helm-api
    cfcRouterUrl: https://icp-management-ingress:443
    hcmSearchApiUrl: https://search-search-api:4010/searchapi
    hcmUiApiUrl: https://mcm-312-ibm-mcm-prod-mcmuiapi:4000/hcmuiapi
    platformidentityproviderurl: https://icp-management-ingress:443/idprovider
    wlpredirecturl: http://localhost:3000/auth/liberty/callback
  healthcheck:
    enabled: false
  image:
    name: catalog-ui
    pullPolicy: IfNotPresent
    repository: quay.io/opencloudio/icp-catalog-ui@sha256:de2fa95e29e4b71d9ded6aa60a6f093b4dd9c3bd7643a55845b3822db618633e
  ingresspath: /catalog/
  resources:
    limits:
      cpu: 300m
      memory: 300Mi
    requests:
      cpu: 300m
      memory: 300Mi
  secretKeyRef:
    clientIdSecretKey: WLP_CLIENT_ID
    clientIdSecretName: platform-oidc-credentials
    clientSecretSecretKey: WLP_CLIENT_SECRET
  service:
    name: catalog-ui
    port: 4000
    servicePort: 4000
    targetPort: 4000
  tolerations:
  - effect: NoSchedule
    key: dedicated
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
