---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.catalogui.commonname }}
  labels:
    app: {{ .Values.catalogui.commonname  }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    component: "catalogui"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service}}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: catalog-ui
  template:
    metadata:
      labels:
        app: {{ .Values.catalogui.commonname }}
        app.kubernetes.io/instance: "{{ .Release.Name }}"
        chart: "{{ .Chart.Name }}"
        component: "catalogui"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service}}
        k8s-app: {{ .Values.catalogui.commonname }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
      annotations:
        productName: IBM Cloud Platform Common Services
        productID: "068a62892a1e4db39641342e592daa25"
        productMetric: FREE
        clusterhealth.ibm.com/dependencies: "auth-idp, helm-api, helm-repo, platform-api, platform-header"
    spec:
      serviceAccount: ibm-catalog-ui-operand
      serviceAccountName: ibm-catalog-ui-operand
      terminationGracePeriodSeconds: 60
      hostNetwork: false
      hostPID: false
      hostIPC: false
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: beta.kubernetes.io/arch
                  operator: In
                  values:
                  - amd64
                  - ppc64le
                  - s390x
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - {{ .Values.catalogui.commonname }}
            topologyKey: "kubernetes.io/hostname"
    {{- if .Values.catalogui.tolerations }}
      tolerations:
{{ toYaml .Values.catalogui.tolerations | indent 8 }}
    {{- end }}
      initContainers:
        - name: check-secret
          image: {{ .Values.catalogui.image.repository }}
          imagePullPolicy: {{ .Values.catalogui.image.pullPolicy }}
          volumeMounts:
            - name: check-file
              mountPath: /check-file
          resources:
{{ toYaml .Values.catalogui.resources | indent 12 }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop:
              - ALL
          command:
            - sh
            - -c
            - |
              while true; do
                ls /check-file/* && break
                sleep 30
              done
      containers:
        - name: {{ .Values.catalogui.image.name }}
          image: {{ .Values.catalogui.image.repository }}
          imagePullPolicy: {{ .Values.catalogui.image.pullPolicy }}
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            privileged: false
            capabilities:
              drop:
              - ALL
          env:
            - name: cfcRouterUrl
              value: "{{ .Values.catalogui.env.cfcRouterUrl }}"
            - name: catalogApiRouteUrl
              value: "{{ .Values.catalogui.env.catalogApiRouteUrl }}"
            - name: WLP_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  optional: true
                  name: {{ .Values.catalogui.secretKeyRef.clientIdSecretName }}
                  key: {{ .Values.catalogui.secretKeyRef.clientIdSecretKey }}
            - name: WLP_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.catalogui.secretKeyRef.clientIdSecretName }}
                  key: {{ .Values.catalogui.secretKeyRef.clientSecretSecretKey }}
            - name: PLATFORM_IDENTITY_PROVIDER_URL
              value: "{{ .Values.catalogui.env.platformidentityproviderurl }}"
            - name: WLP_REDIRECT_URL
              value: "{{ .Values.catalogui.env.wlpredirecturl }}"
            - name: hcmUiApiUrl
              value: "{{ .Values.catalogui.env.hcmUiApiUrl }}"
            - name: hcmSearchApiUrl
              value: "{{ .Values.catalogui.env.hcmSearchApiUrl }}"
          resources:
{{ toYaml .Values.catalogui.resources | indent 12 }}
          {{- if .Values.catalogui.healthcheck.enabled }}
          livenessProbe:
            httpGet:
              port: 4000
              path: /catalog/livenessProbe
              scheme: HTTP
            failureThreshold: 9
            initialDelaySeconds: 185
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              port: 4000
              path: /catalog/readinessProbe
              scheme: HTTP
            failureThreshold: 9
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          {{- end }}
      volumes:
        - name: check-file
          secret:
            optional: true
            secretName: {{ .Values.catalogui.secretKeyRef.clientIdSecretName }}
