apiVersion: v1
kind: ServiceAccount
metadata: 
  name: catalog-ui-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: catalog-ui-privileged-role
rules:
- apiGroups:
  - security.openshift.io 
  resources:
  - securitycontextconstraints 
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: catalog-ui-privileged
subjects:
- kind: ServiceAccount
  name: catalog-ui-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: catalog-ui-privileged-role