apiVersion: v1
kind: ServiceAccount
metadata: 
  name: ibm-catalog-ui-operand
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ .Values.catalogui.commonname }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"